import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body>
        <nav className="bg-blue-600 text-white p-4 text-center">
          <Link href="/" className="mx-4 hover:underline">Accueil</Link>
          <Link href="/about" className="mx-4 hover:underline">À propos</Link>
          <Link href="/contact" className="mx-4 hover:underline">Contact</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}